### ISSUE TITLE
REVIEW

### ISSUE THREAD

**Issue by InfectedDevAnna** [s1dharth-s/containercraft#2]
1. The project's topic was to create a Linux development enviroment using Dockers. It is supposed to make it easier for companies that have a lot of temporary workers, students for example, that switch a lot. This program provides users with the setup that is the same for every user, so you can make sure whatever was developed would run on such setup.
2. Unfortunately I was not able to reproduce it because the artifact file is empty. I can not clone the repository on Linux because I get the authentification errors. And I don't seem to be able to fix it. (It is also my work laptop, so maybe it is for the security reasons). If the artifact file wasn't empty it would have been fine for me to run it.
3. The code is nicely commented. There are also some simple tests. 
I don't have much to say since this project is very well structured. The README file explaines what it does and provides very clear instructions on how to install it all and how to run it. 
The bash sctipt setup.sh allows you to install all the packages and dependencies with just one command.

**Comment by s1dharth-s** [comment]
I believe the artifact folder was empty because in my project repository (https://github.com/freiburg-missing-semester-course/project-s1dharth-s), I added this repo as a submodule. I have updated a tag in the current repository as well, and you can try replicating the artifact by downloading it. I apologize for the confusion.

Also, I think your review should be posted on https://github.com/freiburg-missing-semester-course/project-s1dharth-s and not here (this is my personal repository).

**Comment by InfectedDevAnna** [comment]
Oh thank you!
I didn't even noticed, I did it here, sorry
